[package]
name = "mars"
version = "0.1.0"
authors = ["wintermute"]
edition = "2018"

[dependencies]
minifb = "*"
#{ git = "/Users/tucker_morgan/Documents/rust_minifb"}
nalgebra = "0.16.0"
rand = "*"
image = "*"