[package]
name = "mars"
version = "0.1.0"
authors = ["marsmute"]
edition = "2018"

[dependencies]
minifb = "*"
rand = "*"
image = "*"
spmc = "*"
num_cpus = "1.0"
rayon = "1.0"
glam = "0.6.1"

[profile.release]
lto = true
codegen-units = 1